arch:
  - arm64
os: linux
dist: bionic
language: rust
cache: cargo
rust:
  - stable
matrix:
  fast_finish: false
  script:
    run:
      - cargo build --verbose
      - cargo test --verbose
      - cargo doc --verbose